// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnZCNrKJn2VYgwcNAge39ng0bKOpvudAA',
    appId: '1:710947816899:web:e7447b998b2606d79c6976',
    messagingSenderId: '710947816899',
    projectId: 'get-pos-49a30',
    authDomain: 'get-pos-49a30.firebaseapp.com',
    storageBucket: 'get-pos-49a30.appspot.com',
    measurementId: 'G-W7DHG3QCES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8nD69qfA1pknANn9Fj-gtp8C8knXcKWo',
    appId: '1:710947816899:android:51b9c734131da2419c6976',
    messagingSenderId: '710947816899',
    projectId: 'get-pos-49a30',
    storageBucket: 'get-pos-49a30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR5i1pjefmtabBXwStAhVqD6WPJGzcN9g',
    appId: '1:710947816899:ios:382331a2135f6a359c6976',
    messagingSenderId: '710947816899',
    projectId: 'get-pos-49a30',
    storageBucket: 'get-pos-49a30.appspot.com',
    iosClientId: '710947816899-6p71jpi57rhep6ok0ea6r53h4eo97bul.apps.googleusercontent.com',
    iosBundleId: 'com.nestorbird.nb-pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR5i1pjefmtabBXwStAhVqD6WPJGzcN9g',
    appId: '1:710947816899:ios:d2c4978cd5ea266f9c6976',
    messagingSenderId: '710947816899',
    projectId: 'get-pos-49a30',
    storageBucket: 'get-pos-49a30.appspot.com',
    iosClientId: '710947816899-4fup9uksi2bpco8iaaurn3ku478u007b.apps.googleusercontent.com',
    iosBundleId: 'com.nestorbird.nbPosx',
  );
}
